config/routes.rb
Rails.application.routes.draw do

  get 'tasks/list', to: "tasks#user_tasks"
  get 'user/login_show', to: "users#login_page"
  post 'tasks/complete', to: "tasks#task_completed", as: 'update_tasks' , :defaults => { :format => 'json' }

  get 'users/login', to: "users#login" , :defaults => { :format => 'xml' }
  get 'tasks/all_tasks', to: "tasks#all_tasks"
  get 'tasks/task_user', to: "tasks#task_user"
  get 'tasks/score_board', to: "tasks#score_board"

  resources :users
  resources :tasks
  root to: "users#home"

end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :users, through: :task_users
  has_many :task_users

  # def self.score_board
  #   @users = User.all
  #   @users.each do |user|
  #     user.points = user.tasks.sum(:points)
  #     user.save!
  #     @users = User.all.collect{ |x| x.tasks.sum(:points) }
  #   end
  # end

end

app/models/task_user.rb
class TaskUser < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :task_users
  # association between users and tasks
  has_many :tasks, through: :task_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_filter :auth_valid_token
  
  def all_tasks
    @tasks = Task.find_by status: true
    respond_to do |format|
      format.html { render template: 'task_user' }
      format.json { render json: @tasks }
      format.xml { render xml: @tasks }
    end
  end

  def user_pending
    user = get_user
    @tasks = TaskUser.where("created_at > ? AND user_id = ?", Time.now-24.hours, user.id).pluck(:id)
    @pending_tasks = Task.where('id not in (?) and status = 1', @tasks)
    respond_to do |format|
      format.json { render json: @pending_tasks }
      format.xml { render xml: @pending_tasks }
    end
  end

  def task_completed
    user = get_user    
    task = user.tasks.find(params[:task_id])
    user.points = user.points.to_i + task.points.to_i
    user.save!
    task.status = !task.status
    task.save!
    respond_to do |format|
      format.json { render json: {status: true} }
    end    
  end

  def score_board
    @users = User.all
    @users.each do |user|
      user.points = user.tasks.sum(:points)
      user.save!
    end
  end

  def user_tasks
    user = get_user
    @tasks = user.tasks.where(:status => true)
    render :task_user
  end

  def show
    @users = User.all
    @users.each do |user|
      user.points = user.tasks.sum(:points)
    end
    @users = @users.sort_by{ |hsh| hsh[:points] }.reverse


    # email = params[:email]
    # user = User.find_by email: email
    # if user
    #   @tasks = TaskUser.where("created_at > ?", Time.now-24.hours)
    # else
    #   @tasks = {status => "500"}
    # end
    # # respond_to do |format|
    # #   format.json { render json: @tasks }
    # #   format.xml { render xml: @tasks }
    # # end
  end
  
  # We don't need this method because points are updated on completion of task

  # def add_points
  #   user = get_user
  #   new_points = params[:points]
  #   user.points = user.points.to_i + new_points.to_i
  #   user.save!
  # end

  def auth_valid_token
    auth_token = params[:token]
    user = User.where(:auth_token => auth_token).first
    if user
      return true
    else
      return false
    end

  end

  def get_user
    auth_token = params[:token]
    user = User.where(:auth_token => auth_token).first
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #http_basic_authenticate_with :name => "myfinance", :password => "credit123"
  #skip_before_filter :login
  #before_filter :auth_valid_token , :except => [:login, :home, :create]
  protect_from_forgery

  def fetch_user
    @user = User.find_by_id(params[:id])
  end

  def login_page
  end

  def login
    email = params[:email]
    password = params[:password]
    @auth_token = Digest::MD5.hexdigest(email+password)
    @user = User.find_by auth_token: @auth_token
    if @auth_token = @user.auth_token
      @tasks = @user.tasks
      respond_to do |format|
        format.json { render json: @user }
        format.xml { render xml: @user }
      end
      # @token_hash = {'status'=> '200','auth_token' => @auth_token}
      # user = User.new(:email => email, :password => password, :auth_token => @auth_token)
      # user.save
    end

    # respond_to do |format|
    #   format.json { render json: @token_hash }
    #   format.xml { render xml: @token_hash }
    # end
  end

  def index
    @users = User.all
    respond_to do |format|
      format.json { render json: @users }
      format.xml { render xml: @users }
    end
  end

  def home
    @user = User.new
  end


  def show
    @user = User.find_by_auth_token(params[:auth_token])
    respond_to do |format|
      format.json { render json: @user }
      format.xml { render xml: @user }
      format.html
    end
  end

  def create
    @user = User.new(user_params)
    @auth_token = Digest::MD5.hexdigest(@user.email+@user.password)
    @user.auth_token = @auth_token
    @user.save
    respond_to do |format|
      if @user.save
        format.json { render json: @user, status: :created }
        format.xml { render xml: @user, status: :created }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.xml { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def auth_valid_token
    auth_token = params[:token]
    user = User.find(:auth_token => 'auth_token')
    if user
      return true
    else
      return false
    end
  end

  private
  ## Strong Parameters
  def user_params
    params.require(:user).permit(:email,:password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AndApi</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/tasks/score_board.html.haml
- @users.each do |user|
	%div
		%p= user.email
		%p= user.points

app/views/tasks/show.html.haml
.container
  - @users.each do |user|
    .list
      .user_name= user.username
      .user_points= user.points

app/views/tasks/task_user.html.haml
.tasks_container
	- if @tasks.empty?
		.tasks_success= "Congratulations! You have completed all your tasks."
	- else
		= form_tag update_tasks_path, id:"task_form", remote: true, format: 'json' do
			- @tasks.each do |task|
				.task_item_container
					= check_box_tag "task_id", task.id, false, options = {class: "task_item", id: "task_#{task.id}"}
					= label_tag "task_#{task.id}", task.task_name
			= hidden_field_tag :token, params[:token]

	:javascript
		$(function(){
			var clicked = "";

			$(".task_item").on('change', function(){
				$("#task_form").submit();
				clicked = $(this).attr("id");
			});

			$(document).on("ajax:success","#task_form", function(xhr, data, status){
				console.log(data);
				if(clicked && data.status)
				{
					$("#"+clicked).parents(".task_item_container").fadeOut();
				}
			});

		});

app/views/tasks/tasks_all.html.haml
hello

app/views/users/home.html.erb
<h1>New User</h1>
 

<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/login.html.erb
caacdsdsadasdsadsa
<%= @token_hash %>

app/views/users/login_page.html.erb
<div class="container">

  <div class="form_input">
    <label>Email</label>
    <input type="text" id="email">
  </div>

  <br>
  <div class="form_input">
    <label>Password</label>
    <input type="password" id="password">
  </div>

  <button class="btn" id="btnqwe">Login</button>
  <script type="text/javascript">
  $(document).on('click','#btnqwe',function(data){
    var password = $('#password').val();
    var email = $('#email').val();
      $.get("http://android.geniilabs.in/users/login.json",{email:email,password:password},function(data){
          console.log(data);
          var auth_token = data.auth_token;
          Android.addtoken(auth_token);
        });

      return false;
  });
  </script>

</div>

app/views/users/show.html.haml
.container
  .user-profile-page

    .profile_img
      %img{src: "http://www.vslots.co.za/wp-content/uploads/2011/11/blank-gravatar.jpg"}

    %p.profile_name
      = @user.username

    %p.profile_email
      = @user.email

    %p.first-row
      Points:
      = @user.points